version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    environment:
     - DBURL=mongodb://db:27017/sabre
  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
